#!/usr/bin/env bash
# Installs nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#   it must return a page that contains the string Hello World!
# You can’t use systemctl for restarting nginx

echo -e "Installing and Configuring Nginx\n"
sudo apt-get update -y && \
         sudo apt-get install nginx -y

# Starting Nginx
sudo service nginx start

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Giving user ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backing up default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nProcess Complete. ✅\n"
