#!/usr/bin/env bash
# Configures the Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
# Using 1-install_nginx_web_server, write 3-redirection so that it configures a
#     brand new Ubuntu machine to the requirements asked in this task

echo -e "Installing and Configuring Nginx\n"
sudo apt-get update -y && \
         sudo apt-get install nginx -y

# Starting Nginx
sudo service nginx start

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Giving user ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backing up default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a different page
sudo sed -i '24i\      rewrite ^/redirect_me https://www.youtube.com/watch?v=vYqLz3GVN4Q&t=295s permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nProcess Complete. ✅\n"
