#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

function install() {
	command -v "$1" &> /dev/null

	# Ignore SC2154 for shellcheck
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}
# Installing haproxy
install haproxy 

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend lizzieakinyi-tech-frontend
    bind *:80
    default_backend lizzieakinyi-tech-backend

backend lizzieakinyi-tech-backend
    balance roundrobin
    server 151666-web-01 54.234.101.144:80 check
    server 151666-web-02 54.89.28.233:80 check
"

# Ignore SC2154 for shellcheck
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
