#!/usr/bin/env bash
#Stops 4-to_infinity_and_beyond process
#   Requirements:
#     You must use kill

#method 1:
#kill "$(pgrep -f 4-to_infinity_and_beyond)"

#method 2:
pgrep -f 4-to_infinity_and_beyond | xargs kill
