#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS
#   Parses the "/etc/passwd" file, extracts specific fields for each user, assigns them to variables, and then prints out formatted info about each user

#method 1
#while IFS=':' read -r username password uid gid info home shell;
#do
#  echo "The user $username is part of the $gid gang,"\
#  "lives in $home and rides $shell."\
#  "$uid's place is protected by the passcode $password,"\
#  "more info about the user here: $info"
#done < "/etc/passwd"

contentFile="/etc/passwd" #contentFile - contains the path of the "/etc/passwd" file
f1="" # fields - variables to store different fields extracted from each line of the "/etc/passwd" file
f2=""
f3=""
while IFS= read -r line # loop - reads each line from the file stored in the contentFile
do
    f1="$(echo "$line" | cut -d":" -f1)" # cut command extracts specific fields separated by colons (':')
    f2="$(echo "$line" | cut -d":" -f4)" # each field is assigned to a different variable
    f3="$(echo "$line" | cut -d":" -f6)"
    f4="$(echo "$line" | cut -d":" -f7)"
    f5="$(echo "$line" | cut -d":" -f3)"
    f6="$(echo "$line" | cut -d":" -f2)"
    f7="$(echo "$line" | cut -d":" -f5)"
# line printsout formatted info about each user using values stored in the variables (fields)
    echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f4}. ${f5}'s place is protected by the passcode ${f6}, more info about the user here: ${f7}"
done < "$contentFile"
