#!/usr/bin/env bash
# Groups (sorts) visitors by IP and HTTP status code, and displays the data
# (uses the data parsed from the Apache log file in 102-lets_parse_apache_logs)
# The exact format must be:
#     OCCURENCE_NUMBER IP HTTP_CODE
#     In list format
#   Ordered from the greatest to the lowest number of occurrences
# You must use awk (You are not allowed to use while, for, until and cut)

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
