#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration
#   displays Best School and then Hi on a new line

iterator=0

while [ $iterator -lt 10 ]
do
  if [ $iterator -eq 9 ]
  then
    echo "Hi";
  fi
  echo "Best School";
  (( iterator++ ))
done
