#!/usr/bin/env bash
# Displays using the for loop, the content of the current directory
#  In a list format
#   Where only the part of the name after the first dash is displayed

list=$(ls)
for directory_content in $list
do
  echo "$directory_content" | cut -d '-' -f2
done
